notifications:
  email: false
sudo: enabled
os: linux
language: python
cache: pip
python: 3.8-dev
env:
  global:
    - GH_REPO=Drakkar-Software/OctoBot-IA-Tentacles
    - DEPLOY_BRANCH=0.4.0
    - LATEST_TAG=latest
    - DEPLOY_URL=https://www.tentacles.octobot.online/repository/tentacles/officials/IA

matrix:
  include:
    - name: "Linux - Python 3 nightly"
      stage: test
      os: linux
      python: 3.8
      language: python
      script: echo "TODO"

    - name: "Linux - Tentacles - Deploy"
      stage: deploy
      os: linux
      install: skip
      script:
        - mkdir reference_tentacles
        - cp -r Evaluator reference_tentacles
        - zip -9 -q -r $LATEST_TAG.zip reference_tentacles
      deploy:
        - provider: script
          script: mv $LATEST_TAG.zip $TRAVIS_TAG.zip && curl -v --user "$NEXUS_USERNAME:$NEXUS_PASSWORD" --upload-file ./$LATEST_TAG.zip  $DEPLOY_URL/$TRAVIS_TAG.zip
          skip_cleanup: true
          cleanup: false
          on:
            repo: "$GH_REPO"
            tags: true
            branch: "$DEPLOY_BRANCH"
        - provider: script
          script: curl -v --user "$NEXUS_USERNAME:$NEXUS_PASSWORD" --upload-file ./$LATEST_TAG.zip  $DEPLOY_URL/$LATEST_TAG.zip
          skip_cleanup: true
          cleanup: false
          on:
            repo: "$GH_REPO"
            tags: false
            branch: "$DEPLOY_BRANCH"
